options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args:
      - '-c'
      - |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${_GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${_GITHUB_REPO}/pulls/${_GITHUB_PR_NUMBER} \
          -d '{"body":"Cloud Build finished successfully!"}'
