options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: hashicorp/terraform:1.14
    args:
      - init
  - name: hashicorp/terraform:1.14
    args:
      - plan
      - -out=/workspace/tfplan
  - name: bash
    script: echo "\`\`\`" > /workspace/tfplan.txt
  - name: hashicorp/terraform:1.14
    entrypoint: sh
    args:
      - '-c'
      - |
        TF_PLAN=$(terraform show -no-color /workspace/tfplan)
        TF_PLAN="${TF_PLAN//$'\n'/\\\n}"
        TF_PLAN="${TF_PLAN//\"/\\\"}"
        echo -n "${TF_PLAN}" >> /workspace/tfplan.txt
  - name: bash
    script: echo "\`\`\`" >> /workspace/tfplan.txt
  - name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args:
      - '-c'
      - |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${_GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${_GITHUB_REPO}/pulls/${_GITHUB_PR_NUMBER} \
          -d "{\"body\":\"$$(</workspace/tfplan.txt)\"}"
