options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: us-central1-docker.pkg.dev/bootstrap-wjz4/cloud-build/primary:latest
    args:
      - init
  - name: us-central1-docker.pkg.dev/bootstrap-wjz4/cloud-build/primary:latest
    args:
      - plan
      - -out=/workspace/tfplan
  - name: us-central1-docker.pkg.dev/bootstrap-wjz4/cloud-build/primary:latest
    entrypoint: sh
    args:
      - '-c'
      - |
        echo -n "# Terraform Plan File\\n\\n\`\`\`\\n" > /workspace/tfplan.txt
        TF_PLAN=$(terraform show -no-color /workspace/tfplan)
        TF_PLAN="$${TF_PLAN//$$'\n'/\\\n}"
        TF_PLAN="$${TF_PLAN//$$'\r'/}"
        TF_PLAN="$${TF_PLAN//\"/\\\"}"
        echo -n "$${TF_PLAN}" >> /workspace/tfplan.txt
        echo -n "\`\`\`" >> /workspace/tfplan.txt
        cat /workspace/tfplan.txt
  - name: us-central1-docker.pkg.dev/bootstrap-wjz4/cloud-build/primary:latest
    entrypoint: bash
    args:
      - '-c'
      - |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${_GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${_GITHUB_REPO}/pulls/${_GITHUB_PR_NUMBER} \
          -d "{\"body\":\"$$(</workspace/tfplan.txt)\"}"
