options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: us-central1-docker.pkg.dev/bootstrap-wjz4/cloud-build/primary:latest
    args:
      - init
  - name: us-central1-docker.pkg.dev/bootstrap-wjz4/cloud-build/primary:latest
    args:
      - apply
      - -auto-approve
